title: root@chaoticgeni.us
author: Julio Gonzalez
email: ayreon2k6@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
 Administrador de sistemas especializado en ciencias de datos, usare este espacio para escribir sobre muchos temas tanto tecnicos como opiniones o ideas sin sentido que quiera escribir
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: chaoticgeniu5

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/chaoticgeniu5
      icon: twitter-square
      color: cyan
    - url: https://dba.mx
      icon: itch-io
      color: red
    - url: https://github.com/chaoticgeniu5
      icon: github-square
      color: purple

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
